name: TAORi
favicon: null
layout_spectrum: 0.15746926609426737
typography_spectrum: 0.19153691758401692
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#191a1c'
    - '#ffffff'
    - '#cdcdce'
    - '#7c7d7e'
    - '#60af07'
  brandStrength: 0.8409116165712476
  lightness: 0.757093150401488
  saturation: 0.35871996148489416
  rhythmicContrast: 0.08105342625640333
purpose: []
